export const actionTypes = {
  SET_IMAGES: "SET_IMAGES",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERROR: "SET_ERROR",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  SET_IS_FETCHED: "SET_IS_FETCHED",
  SET_PAGE: "SET_PAGE",
};
